token.jsonの存在確認

diff --git a/.github/workflows/update-photos.yaml b/.github/workflows/update-photos.yaml
--- a/.github/workflows/update-photos.yaml
+++ b/.github/workflows/update-photos.yaml
@@ -21,7 +21,12 @@ jobs:
           TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
         run: |
           echo "$TOKEN_JSON" | jq . > ci/token.json
-          echo "Token saved to ci/token.json"
+          if [ ! -f "ci/token.json" ]; then \
+            echo "Error: ci/token.json does not exist." \
+            exit 1 \
+          else \
+            echo "Token saved to ci/token.json" \
+          fi
 
       - name: pipインストール
         run: |
